// Code generated by protoc-gen-go. DO NOT EDIT.
// This is a stub file. Run `protoc` to generate the actual file.

package proto

type FaceDetectionRequest struct {
	VideoPath  string
	SampleRate int32
}

type FaceDetectionResponse struct {
	AvgFaceCount float64
	MaxFaceCount int32
	MinFaceCount int32
	FrameResults []*FrameFaceResult
}

type FrameFaceResult struct {
	TimestampMs int32
	FaceCount   int32
}

type SpeakerAnalysisRequest struct {
	VideoPath string
}

type SpeakerAnalysisResponse struct {
	SpeakerCount  int32
	DialogueRatio float64
	Segments      []*SpeakerSegment
}

type SpeakerSegment struct {
	StartMs   int32
	EndMs     int32
	SpeakerId int32
}
