// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// This is a stub file. Run `protoc` to generate the actual file.

package proto

import (
	"context"

	"google.golang.org/grpc"
)

type MLServiceClient interface {
	DetectFaces(ctx context.Context, in *FaceDetectionRequest, opts ...grpc.CallOption) (*FaceDetectionResponse, error)
	AnalyzeSpeakers(ctx context.Context, in *SpeakerAnalysisRequest, opts ...grpc.CallOption) (*SpeakerAnalysisResponse, error)
}

type mLServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMLServiceClient(cc grpc.ClientConnInterface) MLServiceClient {
	return &mLServiceClient{cc}
}

func (c *mLServiceClient) DetectFaces(ctx context.Context, in *FaceDetectionRequest, opts ...grpc.CallOption) (*FaceDetectionResponse, error) {
	out := new(FaceDetectionResponse)
	err := c.cc.Invoke(ctx, "/ml.MLService/DetectFaces", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLServiceClient) AnalyzeSpeakers(ctx context.Context, in *SpeakerAnalysisRequest, opts ...grpc.CallOption) (*SpeakerAnalysisResponse, error) {
	out := new(SpeakerAnalysisResponse)
	err := c.cc.Invoke(ctx, "/ml.MLService/AnalyzeSpeakers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}
